version: '3'
services:
  nest-api-docker:
    environment:
      - NODE_ENV=development
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/app
    container_name: ffwb_server
    expose:
      - "3000"
    ports:
      - "3000:3000"